import React, { useEffect, useMemo, useState } from 'react';
import api from '../../utils/api';
import { useAuth } from '../../context/AuthContext';

const today = () => new Date().toISOString().slice(0, 10);
const emptyForm = { customer_id: '', invoice_date: today(), due_date: '', item_name: 'ERP Software Service', quantity: 1, unit_price: 50000, discount_amount: 0, status: 'draft', notes: '' };
const badges = { draft: 'badge-blue', sent: 'badge-teal', paid: 'badge-green', overdue: 'badge-red', cancelled: 'badge-yellow' };
const currency = v => Number(v || 0).toLocaleString('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });

const SalesInvoiceModule = () => {
  const { hasRole } = useAuth();
  const [invoices, setInvoices] = useState([]);
  const [customers, setCustomers] = useState([]);
  const [summary, setSummary] = useState(null);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [form, setForm] = useState(emptyForm);
  const [showForm, setShowForm] = useState(false);
  const [loading, setLoading] = useState(true);
  const canManage = hasRole('admin', 'finance_manager');
  const totals = useMemo(() => { const subtotal = Number(form.quantity || 0) * Number(form.unit_price || 0); const tax = Math.round(subtotal * 0.18); const discount = Number(form.discount_amount || 0); return { subtotal, tax, discount, total: subtotal + tax - discount }; }, [form]);

  const load = async () => { setLoading(true); try { const [i,c,s] = await Promise.all([api.get('/sales/invoices', { params: { search, status } }), api.get('/crm/customers'), api.get('/sales/summary')]); setInvoices(i.data); setCustomers(c.data); setSummary(s.data); } catch (_) { setInvoices([]); setCustomers([]); setSummary(null); } finally { setLoading(false); } };
  useEffect(() => { const t = setTimeout(load, 250); return () => clearTimeout(t); }, [search, status]);
  const save = async e => { e.preventDefault(); try { await api.post('/sales/invoices', { customer_id: form.customer_id || null, invoice_date: form.invoice_date, due_date: form.due_date || null, items: [{ name: form.item_name, quantity: Number(form.quantity), unit_price: Number(form.unit_price) }], subtotal: totals.subtotal, tax_amount: totals.tax, discount_amount: totals.discount, status: form.status, notes: form.notes }); setForm(emptyForm); setShowForm(false); load(); } catch (err) { alert(err.response?.data?.error || 'Failed to create invoice.'); } };
  const updateStatus = async (invoice, value) => { try { await api.put(`/sales/invoices/${invoice.id}/status`, { status: value }); load(); } catch (err) { alert(err.response?.data?.error || 'Failed to update invoice.'); } };

  return <div><div className="page-header"><div><p className="eyebrow">Sales Operations</p><h1 className="page-title">Sales and Invoice Module</h1><p className="page-subtitle">Create customer invoices, calculate tax, and monitor paid or outstanding billing.</p></div>{canManage && <button className="btn btn-primary" onClick={() => setShowForm(true)}>+ New Invoice</button>}</div>
    <div className="grid grid-4" style={{ marginBottom: 20 }}><div className="card metric-card" style={{ '--metric-color': '#2563eb', '--metric-soft': '#dbeafe' }}><div className="metric-top"><p className="metric-label">Invoices</p><span className="metric-icon">▤</span></div><p className="metric-value">{summary?.invoice_count ?? invoices.length}</p><p className="metric-sub">Total bills</p></div><div className="card metric-card" style={{ '--metric-color': '#16a34a', '--metric-soft': '#dcfce7' }}><div className="metric-top"><p className="metric-label">Sales</p><span className="metric-icon">₹</span></div><p className="metric-value">{currency(summary?.total_sales)}</p><p className="metric-sub">Invoice value</p></div><div className="card metric-card" style={{ '--metric-color': '#0891b2', '--metric-soft': '#cffafe' }}><div className="metric-top"><p className="metric-label">Paid</p><span className="metric-icon">✓</span></div><p className="metric-value">{currency(summary?.paid_amount)}</p><p className="metric-sub">Received amount</p></div><div className="card metric-card" style={{ '--metric-color': '#d97706', '--metric-soft': '#fef3c7' }}><div className="metric-top"><p className="metric-label">Outstanding</p><span className="metric-icon">!</span></div><p className="metric-value">{currency(summary?.outstanding_amount)}</p><p className="metric-sub">Pending collection</p></div></div>
    <div className="toolbar"><div className="toolbar-left"><input className="input search-input" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search invoice/customer..." /><select className="select" value={status} onChange={e => setStatus(e.target.value)}><option value="">All status</option><option value="draft">Draft</option><option value="sent">Sent</option><option value="paid">Paid</option><option value="overdue">Overdue</option><option value="cancelled">Cancelled</option></select></div><span className="badge badge-green">Invoice Tracking</span></div>
    <div className="card table-card">{loading ? <div className="loading-state"><div><div className="loading-spinner" /><p>Loading invoices...</p></div></div> : <div className="table-scroll"><table className="data-table"><thead><tr><th>Invoice</th><th>Customer</th><th>Date</th><th>Due</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{invoices.map(i => <tr key={i.id}><td><div className="primary-cell">{i.invoice_no}</div><div className="muted-cell">{i.notes || 'Sales invoice'}</div></td><td>{i.customer_name || 'Walk-in'}</td><td>{i.invoice_date ? new Date(i.invoice_date).toLocaleDateString('en-IN') : '—'}</td><td>{i.due_date ? new Date(i.due_date).toLocaleDateString('en-IN') : '—'}</td><td className="primary-cell">{currency(i.total_amount)}</td><td><span className={`badge ${badges[i.status] || 'badge-blue'}`}>{i.status}</span></td><td><select className="select table-select" disabled={!canManage} value={i.status} onChange={e => updateStatus(i, e.target.value)}><option value="draft">Draft</option><option value="sent">Sent</option><option value="paid">Paid</option><option value="overdue">Overdue</option><option value="cancelled">Cancelled</option></select></td></tr>)}</tbody></table></div>}</div>
    {showForm && <div className="modal-backdrop" onClick={() => setShowForm(false)}><div className="modal-card" onClick={e => e.stopPropagation()}><div className="modal-header"><div><h2 className="modal-title">Create Invoice</h2><p className="modal-subtitle">GST style tax is calculated automatically at 18 percent.</p></div><button className="close-btn" onClick={() => setShowForm(false)}>×</button></div><div className="modal-body"><form onSubmit={save}><div className="form-grid"><div className="form-field"><label className="label">Customer</label><select className="select" value={form.customer_id} onChange={e => setForm({ ...form, customer_id: e.target.value })}><option value="">Walk-in</option>{customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="form-field"><label className="label">Invoice Date</label><input className="input" type="date" value={form.invoice_date} onChange={e => setForm({ ...form, invoice_date: e.target.value })} /></div><div className="form-field"><label className="label">Item</label><input className="input" required value={form.item_name} onChange={e => setForm({ ...form, item_name: e.target.value })} /></div><div className="form-field"><label className="label">Quantity</label><input className="input" type="number" min="1" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })} /></div><div className="form-field"><label className="label">Unit Price</label><input className="input" type="number" min="0" value={form.unit_price} onChange={e => setForm({ ...form, unit_price: e.target.value })} /></div><div className="form-field"><label className="label">Status</label><select className="select" value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}><option value="draft">Draft</option><option value="sent">Sent</option><option value="paid">Paid</option></select></div></div><div className="invoice-preview"><span>Subtotal {currency(totals.subtotal)}</span><span>Tax {currency(totals.tax)}</span><strong>Total {currency(totals.total)}</strong></div><div className="form-actions"><button type="button" className="btn btn-secondary" onClick={() => setShowForm(false)}>Cancel</button><button className="btn btn-primary">Create</button></div></form></div></div></div>}
  </div>;
};
export default SalesInvoiceModule;
