import React, { useEffect, useMemo, useState } from 'react';
import api from '../../utils/api';
import { useAuth } from '../../context/AuthContext';
const currency = v => Number(v || 0).toLocaleString('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });
const supplierEmpty = { name: '', email: '', phone: '', address: '' };
const orderEmpty = { supplier_id: '', item_name: 'Office Equipment', quantity: 1, unit_price: 10000, expected_delivery: '', status: 'pending' };
const badges = { pending: 'badge-yellow', confirmed: 'badge-blue', delivered: 'badge-green', cancelled: 'badge-red' };
const SupplierPurchaseModule = () => {
  const { hasRole } = useAuth();
  const [suppliers, setSuppliers] = useState([]); const [orders, setOrders] = useState([]); const [summary, setSummary] = useState(null); const [loading, setLoading] = useState(true); const [tab, setTab] = useState('orders'); const [supplier, setSupplier] = useState(supplierEmpty); const [order, setOrder] = useState(orderEmpty); const [showSupplier, setShowSupplier] = useState(false); const [showOrder, setShowOrder] = useState(false);
  const canManage = hasRole('admin', 'inventory_manager');
  const total = useMemo(() => Number(order.quantity || 0) * Number(order.unit_price || 0), [order]);
  const load = async () => { setLoading(true); try { const [s,o,m] = await Promise.all([api.get('/purchase/suppliers'), api.get('/purchase/orders'), api.get('/purchase/summary')]); setSuppliers(s.data); setOrders(o.data); setSummary(m.data); } catch (_) { setSuppliers([]); setOrders([]); setSummary(null); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const saveSupplier = async e => { e.preventDefault(); try { await api.post('/purchase/suppliers', supplier); setSupplier(supplierEmpty); setShowSupplier(false); load(); } catch (err) { alert(err.response?.data?.error || 'Failed to add supplier.'); } };
  const saveOrder = async e => { e.preventDefault(); try { await api.post('/purchase/orders', { supplier_id: order.supplier_id, status: order.status, expected_delivery: order.expected_delivery || null, items: [{ name: order.item_name, quantity: Number(order.quantity), unit_price: Number(order.unit_price) }] }); setOrder(orderEmpty); setShowOrder(false); load(); } catch (err) { alert(err.response?.data?.error || 'Failed to create purchase order.'); } };
  const updateStatus = async (id, status) => { try { await api.put(`/purchase/orders/${id}/status`, { status }); load(); } catch (err) { alert(err.response?.data?.error || 'Failed to update order.'); } };
  return <div><div className="page-header"><div><p className="eyebrow">Procurement Management</p><h1 className="page-title">Supplier and Purchase Module</h1><p className="page-subtitle">Manage supplier records, purchase orders, delivery tracking and procurement value.</p></div><div className="header-actions">{canManage && <button className="btn btn-secondary" onClick={() => setShowSupplier(true)}>+ Add Supplier</button>}{canManage && <button className="btn btn-primary" onClick={() => setShowOrder(true)}>+ Purchase Order</button>}</div></div>
    <div className="grid grid-4" style={{ marginBottom: 20 }}><div className="card metric-card" style={{ '--metric-color': '#2563eb', '--metric-soft': '#dbeafe' }}><div className="metric-top"><p className="metric-label">Suppliers</p><span className="metric-icon">◫</span></div><p className="metric-value">{summary?.supplier_count ?? suppliers.length}</p><p className="metric-sub">Vendor records</p></div><div className="card metric-card" style={{ '--metric-color': '#7c3aed', '--metric-soft': '#ede9fe' }}><div className="metric-top"><p className="metric-label">Orders</p><span className="metric-icon">▤</span></div><p className="metric-value">{summary?.order_count ?? orders.length}</p><p className="metric-sub">Purchase orders</p></div><div className="card metric-card" style={{ '--metric-color': '#16a34a', '--metric-soft': '#dcfce7' }}><div className="metric-top"><p className="metric-label">Purchase Value</p><span className="metric-icon">₹</span></div><p className="metric-value">{currency(summary?.purchase_value)}</p><p className="metric-sub">Total PO amount</p></div><div className="card metric-card" style={{ '--metric-color': '#d97706', '--metric-soft': '#fef3c7' }}><div className="metric-top"><p className="metric-label">Pending</p><span className="metric-icon">!</span></div><p className="metric-value">{summary?.pending_orders ?? 0}</p><p className="metric-sub">Awaiting delivery</p></div></div>
    <div className="toolbar"><div className="toolbar-left"><button className={`tab-btn ${tab === 'orders' ? 'active' : ''}`} onClick={() => setTab('orders')}>Purchase Orders</button><button className={`tab-btn ${tab === 'suppliers' ? 'active' : ''}`} onClick={() => setTab('suppliers')}>Suppliers</button></div><span className="badge badge-blue">Procurement</span></div>
    <div className="card table-card">{loading ? <div className="loading-state"><div><div className="loading-spinner" /><p>Loading purchase data...</p></div></div> : tab === 'orders' ? <div className="table-scroll"><table className="data-table"><thead><tr><th>PO No</th><th>Supplier</th><th>Items</th><th>Amount</th><th>Delivery</th><th>Status</th><th>Action</th></tr></thead><tbody>{orders.map(o => <tr key={o.id}><td className="primary-cell">PO-{String(o.id).padStart(4,'0')}</td><td>{o.supplier_name}</td><td className="muted-cell">{Array.isArray(o.items) ? o.items.map(i => `${i.name} x ${i.quantity}`).join(', ') : 'Items'}</td><td className="primary-cell">{currency(o.total_amount)}</td><td>{o.expected_delivery ? new Date(o.expected_delivery).toLocaleDateString('en-IN') : '—'}</td><td><span className={`badge ${badges[o.status] || 'badge-blue'}`}>{o.status}</span></td><td><select className="select table-select" disabled={!canManage} value={o.status} onChange={e => updateStatus(o.id, e.target.value)}><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select></td></tr>)}</tbody></table></div> : <div className="table-scroll"><table className="data-table"><thead><tr><th>Supplier</th><th>Email</th><th>Phone</th><th>Address</th></tr></thead><tbody>{suppliers.map(s => <tr key={s.id}><td className="primary-cell">{s.name}</td><td>{s.email || '—'}</td><td>{s.phone || '—'}</td><td className="muted-cell">{s.address || '—'}</td></tr>)}</tbody></table></div>}</div>
    {showSupplier && <div className="modal-backdrop" onClick={() => setShowSupplier(false)}><div className="modal-card" onClick={e => e.stopPropagation()}><div className="modal-header"><div><h2 className="modal-title">Add Supplier</h2><p className="modal-subtitle">Create vendor master record.</p></div><button className="close-btn" onClick={() => setShowSupplier(false)}>×</button></div><div className="modal-body"><form onSubmit={saveSupplier}><div className="form-grid"><div className="form-field"><label className="label">Name</label><input className="input" required value={supplier.name} onChange={e => setSupplier({ ...supplier, name: e.target.value })} /></div><div className="form-field"><label className="label">Email</label><input className="input" value={supplier.email} onChange={e => setSupplier({ ...supplier, email: e.target.value })} /></div><div className="form-field"><label className="label">Phone</label><input className="input" value={supplier.phone} onChange={e => setSupplier({ ...supplier, phone: e.target.value })} /></div><div className="form-field full"><label className="label">Address</label><textarea className="textarea" value={supplier.address} onChange={e => setSupplier({ ...supplier, address: e.target.value })} /></div></div><div className="form-actions"><button type="button" className="btn btn-secondary" onClick={() => setShowSupplier(false)}>Cancel</button><button className="btn btn-primary">Save</button></div></form></div></div></div>}
    {showOrder && <div className="modal-backdrop" onClick={() => setShowOrder(false)}><div className="modal-card" onClick={e => e.stopPropagation()}><div className="modal-header"><div><h2 className="modal-title">Create Purchase Order</h2><p className="modal-subtitle">Add procurement order.</p></div><button className="close-btn" onClick={() => setShowOrder(false)}>×</button></div><div className="modal-body"><form onSubmit={saveOrder}><div className="form-grid"><div className="form-field"><label className="label">Supplier</label><select className="select" required value={order.supplier_id} onChange={e => setOrder({ ...order, supplier_id: e.target.value })}><option value="">Select supplier</option>{suppliers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="form-field"><label className="label">Item</label><input className="input" value={order.item_name} onChange={e => setOrder({ ...order, item_name: e.target.value })} /></div><div className="form-field"><label className="label">Quantity</label><input className="input" type="number" min="1" value={order.quantity} onChange={e => setOrder({ ...order, quantity: e.target.value })} /></div><div className="form-field"><label className="label">Unit Price</label><input className="input" type="number" min="0" value={order.unit_price} onChange={e => setOrder({ ...order, unit_price: e.target.value })} /></div></div><div className="invoice-preview"><strong>Total {currency(total)}</strong></div><div className="form-actions"><button type="button" className="btn btn-secondary" onClick={() => setShowOrder(false)}>Cancel</button><button className="btn btn-primary">Create</button></div></form></div></div></div>}
  </div>;
};
export default SupplierPurchaseModule;
